package image

import (
	"context"
	"fmt"
	"io"
	"os"

	"github.com/containers/image/v5/copy"
	"github.com/containers/image/v5/docker/archive"
	"github.com/containers/image/v5/docker/reference"
	"github.com/containers/image/v5/signature"
	istorage "github.com/containers/image/v5/storage"
	imagetypes "github.com/containers/image/v5/types"
)

// ErrNoValidTag is returned when an image has no tag suitable for export.
var ErrNoValidTag = fmt.Errorf("image export: %w", ErrNotFound)

// Export writes one or more images as a Docker archive tar to the writer.
func (s *Store) Export(names []string, w io.Writer) error {
	tmp, err := os.CreateTemp("", "kogia-export-*.tar")
	if err != nil {
		return fmt.Errorf("image export: create temp: %w", err)
	}

	tmpPath := tmp.Name()

	defer func() { _ = os.Remove(tmpPath) }()

	closeErr := tmp.Close()
	if closeErr != nil {
		return fmt.Errorf("image export: close temp: %w", closeErr)
	}

	// Remove the empty file — archive.NewWriter creates it fresh.
	_ = os.Remove(tmpPath)

	archiveWriter, err := archive.NewWriter(nil, tmpPath)
	if err != nil {
		return fmt.Errorf("image export: create writer: %w", err)
	}

	defer func() { _ = archiveWriter.Close() }()

	policyCtx, err := newInsecurePolicyContext()
	if err != nil {
		return err
	}

	defer func() { _ = policyCtx.Destroy() }()

	for _, name := range names {
		if exportErr := s.exportOne(name, archiveWriter, policyCtx); exportErr != nil {
			return fmt.Errorf("image export %s: %w", name, exportErr)
		}
	}

	finalizeErr := archiveWriter.Close()
	if finalizeErr != nil {
		return fmt.Errorf("image export: finalize: %w", finalizeErr)
	}

	f, openErr := os.Open(tmpPath) //nolint:gosec // tmpPath is generated by us.
	if openErr != nil {
		return fmt.Errorf("image export: open tar: %w", openErr)
	}

	defer func() { _ = f.Close() }()

	_, copyErr := io.Copy(w, f)
	if copyErr != nil {
		return fmt.Errorf("image export: stream: %w", copyErr)
	}

	return nil
}

func (s *Store) exportOne(nameOrID string, archiveWriter *archive.Writer, policyCtx *signature.PolicyContext) error {
	img, err := s.resolve(nameOrID)
	if err != nil {
		return err
	}

	var dstRef imagetypes.ImageReference

	for _, n := range img.Names {
		parsed, parseErr := reference.ParseNormalizedNamed(n)
		if parseErr != nil {
			continue
		}

		tagged, ok := parsed.(reference.NamedTagged)
		if !ok {
			continue
		}

		ref, refErr := archiveWriter.NewReference(tagged)
		if refErr != nil {
			continue
		}

		dstRef = ref

		break
	}

	if dstRef == nil {
		return fmt.Errorf("%w: no valid tag for %s", ErrNoValidTag, nameOrID)
	}

	srcRef, err := istorage.Transport.ParseStoreReference(s.store, img.ID)
	if err != nil {
		return fmt.Errorf("source reference: %w", err)
	}

	_, err = copy.Image(context.Background(), policyCtx, dstRef, srcRef, &copy.Options{
		SourceCtx:      &imagetypes.SystemContext{},
		DestinationCtx: &imagetypes.SystemContext{},
	})
	if err != nil {
		return fmt.Errorf("copy: %w", err)
	}

	return nil
}
