// gen-routes reads api/swagger.yaml and generates:
//   - Handler interface with one method per operation
//   - RegisterRoutes() wiring all routes to a stdlib net/http.ServeMux
//   - NotImplemented struct providing default 501 for every method
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/go-openapi/loads"
	"github.com/go-openapi/spec"
)

const (
	specFile   = "api/swagger.yaml"
	outputFile = "internal/api/gen/routes.go"
)

type route struct {
	method      string // "GET", "POST", etc.
	path        string // swagger path, e.g. "/containers/{name}/json"
	operationID string // e.g. "ContainerInspect"
	summary     string // one-line description
}

func main() {
	root := moduleRoot()

	doc, err := loads.Spec(filepath.Join(root, specFile))
	if err != nil {
		log.Fatalf("loading spec: %v", err)
	}

	swagger := doc.Spec()
	routes := collectRoutes(swagger)

	sort.Slice(routes, func(i, j int) bool {
		return routes[i].operationID < routes[j].operationID
	})

	src := generate(routes)

	formatted, err := format.Source(src)
	if err != nil {
		log.Printf("WARN: gofmt failed, writing raw output: %v", err)

		formatted = src
	}

	outPath := filepath.Join(root, outputFile)

	if mkdirErr := os.MkdirAll(filepath.Dir(outPath), 0o750); mkdirErr != nil {
		log.Fatalf("mkdir: %v", mkdirErr)
	}

	if writeErr := os.WriteFile(outPath, formatted, 0o600); writeErr != nil {
		log.Fatalf("writing %s: %v", outPath, writeErr)
	}

	log.Printf("wrote %s with %d operations", outputFile, len(routes))
}

func collectRoutes(swagger *spec.Swagger) []route {
	var routes []route

	for path := range swagger.Paths.Paths {
		item := swagger.Paths.Paths[path]

		for method, op := range pathOperations(&item) {
			if op.ID == "" {
				log.Printf("WARN: %s %s has no operationId, skipping", method, path)

				continue
			}

			routes = append(routes, route{
				method:      method,
				path:        path,
				operationID: op.ID,
				summary:     op.Summary,
			})
		}
	}

	return routes
}

func pathOperations(item *spec.PathItem) map[string]*spec.Operation {
	ops := map[string]*spec.Operation{}

	if item.Get != nil {
		ops["GET"] = item.Get
	}

	if item.Post != nil {
		ops["POST"] = item.Post
	}

	if item.Put != nil {
		ops["PUT"] = item.Put
	}

	if item.Delete != nil {
		ops["DELETE"] = item.Delete
	}

	if item.Head != nil {
		ops["HEAD"] = item.Head
	}

	if item.Patch != nil {
		ops["PATCH"] = item.Patch
	}

	if item.Options != nil {
		ops["OPTIONS"] = item.Options
	}

	return ops
}

// swaggerToMuxPath converts swagger path params to Go 1.22 ServeMux patterns.
// e.g. "/containers/{id}/json" → "/containers/{id}/json"
// (they happen to use the same syntax).
func swaggerToMuxPath(path string) string {
	return path
}

func generate(routes []route) []byte {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by hack/gen-routes; DO NOT EDIT.\n")
	buf.WriteString("package gen\n\n")
	buf.WriteString("import \"net/http\"\n\n")

	// Handler interface.
	buf.WriteString("// Handler defines all Docker Engine API operations.\n")
	buf.WriteString("type Handler interface {\n")

	for _, r := range routes {
		comment := fmt.Sprintf("%s %s", r.method, r.path)
		if r.summary != "" {
			comment += " — " + r.summary
		}

		fmt.Fprintf(&buf, "\t// %s\n", comment)
		fmt.Fprintf(&buf, "\t%s(w http.ResponseWriter, r *http.Request)\n", r.operationID)
	}

	buf.WriteString("}\n\n")

	// RegisterRoutes function.
	buf.WriteString("// RegisterRoutes wires all Docker Engine API routes to the handler.\n")
	buf.WriteString("func RegisterRoutes(mux *http.ServeMux, basePath string, h Handler) {\n")

	for _, r := range routes {
		muxPath := swaggerToMuxPath(r.path)
		fmt.Fprintf(&buf, "\tmux.HandleFunc(%q+basePath+%q, h.%s)\n", r.method+" ", muxPath, r.operationID)
	}

	buf.WriteString("}\n\n")

	// NotImplemented struct.
	buf.WriteString("// NotImplemented provides default 501 responses for all Handler methods.\n")
	buf.WriteString("// Embed this in your handler struct to satisfy the interface,\n")
	buf.WriteString("// then override individual methods as you implement them.\n")
	buf.WriteString("type NotImplemented struct{}\n\n")

	for _, r := range routes {
		fmt.Fprintf(&buf, "func (NotImplemented) %s(w http.ResponseWriter, _ *http.Request) {\n", r.operationID)
		buf.WriteString("\tw.Header().Set(\"Content-Type\", \"application/json\")\n")
		buf.WriteString("\tw.WriteHeader(http.StatusNotImplemented)\n")
		fmt.Fprintf(&buf, "\t_, _ = w.Write([]byte(`{\"message\":%q}`))\n", r.operationID+" is not implemented")
		buf.WriteString("}\n\n")
	}

	return buf.Bytes()
}

// moduleRoot returns the Go module root directory.
func moduleRoot() string {
	out, err := exec.Command("go", "env", "GOMOD").Output()
	if err != nil {
		log.Fatalf("go env GOMOD: %v", err)
	}

	gomod := strings.TrimSpace(string(out))
	if gomod == "" || gomod == os.DevNull {
		log.Fatal("not inside a Go module")
	}

	return filepath.Dir(gomod)
}
